version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DOMAIN: "http://localhost:8080"
      JWT_SECRET: "write_your_secret"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/db?schema=public"
    depends_on:
      - db

  db:
    image: postgres:14.13-alpine3.20
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
